 /******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: utlrasonic.h
 *
 * Description: Header file for Ultrasonic device
 *
 * Author: Mohamed Ashraf
 *
 *******************************************************************************/


#include "ultrasonic.h"
#include "gpio.h"
#include "icu.h"
#include "util/delay.h"


/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
/* Create configuration structure for ICU driver */
Icu_ConfigType Icu_Config = {F_CPU_8,RISING};

uint16 Icu_HighTime = 0; /* Store ICR High Time */
uint8 Signal_edges = 0; /* Counter for Edges met */

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/* -----------------------------------------------------------------------------
 * [Function Name]: Ultrasonic_init
 * [Description]: Initialize the ICU driver as required.
 * 				  Setup the ICU call back function.
 * 				  Setup the direction for the trigger pin as output pin through the
 *                GPIO driver.
 * [Args]: this function takes void input.
 * [Returns]: this function returns void.
 * ----------------------------------------------------------------------------*/
void Ultrasonic_init(void){

	/* Setup PB5 as output to trigger ultrasonic. */
	GPIO_setupPinDirection(PORTB_ID,PIN5_ID,PIN_OUTPUT);

	/* Setup ICU as specified */
	Icu_init(&Icu_Config);

	/* Setup the ICU call back function. */
	Icu_setCallBack(Ultrasonic_edgeProcessing);
}


/* -----------------------------------------------------------------------------
 * [Function Name]: Ultrasonic_Trigger
 * [Description]: Send the Trigger pulse to the ultrasonic.
 * [Args]: this function takes void input.
 * [Returns]: this function returns void.
 * ----------------------------------------------------------------------------*/
void Ultrasonic_Trigger(void){

	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_HIGH);
	_delay_us(20);
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_LOW);
}

/* -----------------------------------------------------------------------------
 * [Function Name]: Ultrasonic_readDistance
 * [Description]: Send the trigger pulse by using Ultrasonic_Trigger function.
 *				  Start the measurements by the ICU from this moment.
 * [Args]: this function takes void.
 * [Returns]: this function returns 2 bytes number which is the distance measured in centimeters.
 * ----------------------------------------------------------------------------*/
uint16 Ultrasonic_readDistance(void){

	/* Local variable to calculate distance from ICU value*/
	uint16 Ultrasonic_measuredDistance = 0;

	/*  Send the trigger pulse by using Ultrasonic_Trigger function.  */
	Ultrasonic_Trigger();

	/* Calculating the distance */
	if(Signal_edges == 2){
		Ultrasonic_measuredDistance = ceil(Icu_HighTime/58.8);
		Ultrasonic_measuredDistance = Ultrasonic_measuredDistance + (Ultrasonic_measuredDistance * Error_Percentage);
		Signal_edges = 0;
		Icu_HighTime = 0;
	}

	return Ultrasonic_measuredDistance;
}

/* -----------------------------------------------------------------------------
 * [Function Name]: Ultrasonic_edgeProcessing
 * [Description]: This is used to calculate the high time (pulse time) generated by
 *                the ultrasonic sensor.
 *
 * [Args]: this function takes void input.
 * [Returns]: this function returns void.
 * ----------------------------------------------------------------------------*/
void Ultrasonic_edgeProcessing(void){
	Signal_edges++;
	if(Signal_edges == 1){
		Icu_clearTimerValue(); /* Clear timer value to start measurements from the first positive edge */
		Icu_setEdgeDetectionType(FALLING);
	}

	else if(Signal_edges == 2){
		/* storing ICR value */
		Icu_HighTime = Icu_getInputCaptureValue();
		Icu_setEdgeDetectionType(RISING);
	}
}
