 /******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: utlrasonic.h
 *
 * Description: Header file for Ultrasonic device
 *
 * Author: Mohamed Ashraf
 *
 *******************************************************************************/
#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

/*******************************************************************************
 *                            Definitions                                      *
 *******************************************************************************/

#define Error_Percentage (1.25/100)


/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/* -----------------------------------------------------------------------------
 * [Function Name]: Ultrasonic_init
 * [Description]: Initialize the ICU driver as required.
 * 				  Setup the ICU call back function.
 * 				  Setup the direction for the trigger pin as output pin through the
 *                GPIO driver.
 * [Args]: this function takes void input.
 * [Returns]: this function returns void.
 * ----------------------------------------------------------------------------*/
void Ultrasonic_init(void);

/* -----------------------------------------------------------------------------
 * [Function Name]: Ultrasonic_Trigger
 * [Description]: Send the Trigger pulse to the ultrasonic.
 * [Args]: this function takes void input.
 * [Returns]: this function returns void.
 * ----------------------------------------------------------------------------*/
void Ultrasonic_Trigger(void);

/* -----------------------------------------------------------------------------
 * [Function Name]: Ultrasonic_readDistance
 * [Description]: Send the trigger pulse by using Ultrasonic_Trigger function.
 *				  Start the measurements by the ICU from this moment.
 * [Args]: this function takes void.
 * [Returns]: this function returns 2 bytes number which is the distance measured in centimeters.
 * ----------------------------------------------------------------------------*/
uint16 Ultrasonic_readDistance(void);

/* -----------------------------------------------------------------------------
 * [Function Name]: Ultrasonic_edgeProcessing
 * [Description]: This is used to calculate the high time (pulse time) generated by
 *                the ultrasonic sensor.
 *
 * [Args]: this function takes void input.
 * [Returns]: this function returns void.
 * ----------------------------------------------------------------------------*/
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */




